# Generated by Django 2.0.3 on 2018-06-06 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(null=True, verbose_name='終了時間')),
                ('is_worn', models.BooleanField(default=False, verbose_name='装着フラグ')),
                ('note', models.TextField(null=True, verbose_name='メモ')),
            ],
        ),
    ]
