# Generated by Django 2.0.3 on 2018-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_timer', '0003_auto_20180607_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='timerrecord',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
    ]
